name: Run tests

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'qa'
        type: string

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: test output
	run: echo "Hello World"
