name: Run tests

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'qa'
        type: string

jobs:
  run-test:
    name: Run Output
    runs-on: ubuntu-latest
    steps:
      - name: Output
        id: print
        run: |
          echo "Hello World! ${inputs.environment}"
